/*
 * Parvaeres API
 *
 * Parvaeres magic deployment API
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package parvaeres

import (
	"context"
	"errors"

	"github.com/riccardomc/parvaeres/pkg/gitops"
)

// DefaultApiService is a service that implents the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// DeploymentDeploymentIdGet - Get the deployment with id deploymentId
func (s *DefaultApiService) DeploymentDeploymentIdGet(ctx context.Context, deploymentId string) (interface{}, error) {
	// TODO - update DeploymentDeploymentIdGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'DeploymentDeploymentIdGet' not implemented")
}

// DeploymentGet - Get all deployments
func (s *DefaultApiService) DeploymentGet(ctx context.Context, getDeploymentRequest GetDeploymentRequest) (interface{}, error) {
	// TODO - update DeploymentGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'DeploymentGet' not implemented")
}

// DeploymentPost - Create a new deployment
func (s *DefaultApiService) DeploymentPost(ctx context.Context, createDeploymentRequest CreateDeploymentRequest) (interface{}, error) {
	err := gitops.CreateDeployment(createDeploymentRequest)
	if err != nil {
		return CreateDeploymentResponse{
			Error:   true,
			Message: err.Error(),
			Items:   []DeploymentStatus{},
		}, err
	}
	return CreateDeploymentResponse{
		Error:   false,
		Message: "Yo!",
		Items:   []DeploymentStatus{},
	}, nil
}
