/*
 * Parvaeres API
 *
 * Parvaeres magic deployment API
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package parvaeres

type Logs struct {
	Pod string `json:"Pod,omitempty"`

	Container string `json:"Container,omitempty"`

	Logs string `json:"Logs,omitempty"`
}
