/*
 * Parvaeres API
 *
 * Parvaeres magic deployment API
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package parvaeres

type DeploymentStatusType string

// List of DeploymentStatusType
const (
	PENDING  DeploymentStatusType = "PENDING"
	SYNCING  DeploymentStatusType = "SYNCING"
	DEPLOYED DeploymentStatusType = "DEPLOYED"
	ERROR    DeploymentStatusType = "ERROR"
	UNKNOWN  DeploymentStatusType = "UNKNOWN"
)
