/*
 * Parvaeres API
 *
 * Parvaeres magic deployment API
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package parvaeres

type DeploymentStatus struct {
	UUID string `json:"UUID,omitempty"`

	Status DeploymentStatusType `json:"Status,omitempty"`

	LiveURLs []string `json:"LiveURLs,omitempty"`

	Errors []string `json:"Errors,omitempty"`
}
