/*
 * Parvaeres API
 *
 * Parvaeres magic deployment API
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package parvaeres

type GetDeploymentRequest struct {
	UUID string `json:"UUID,omitempty"`

	Filter string `json:"Filter,omitempty"`
}
