/*
 * Parvaeres API
 *
 * Parvaeres magic deployment API
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package parvaeres

type DeploymentStatus struct {
	UUID string `json:"UUID,omitempty"`

	RepoURL string `json:"RepoURL,omitempty"`

	Path string `json:"Path,omitempty"`

	Email string `json:"Email,omitempty"`

	Status DeploymentStatusType `json:"Status,omitempty"`

	LiveURLs []string `json:"LiveURLs,omitempty"`

	Errors []string `json:"Errors,omitempty"`

	LogsURL string `json:"LogsURL,omitempty"`
}
