/*
 * Parvaeres API
 *
 * Parvaeres magic deployment API
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package parvaeres

import (
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// A DefaultApiController binds http requests to an api service and writes the service results to the http response
type DefaultApiController struct {
	service DefaultApiServicer
}

// NewDefaultApiController creates a default api controller
func NewDefaultApiController(s DefaultApiServicer) Router {
	return &DefaultApiController{service: s}
}

// Routes returns all of the api route for the DefaultApiController
func (c *DefaultApiController) Routes() Routes {
	return Routes{
		{
			"DeploymentDeploymentIdGet",
			strings.ToUpper("Get"),
			"/v1/deployment/{deploymentId}",
			c.DeploymentDeploymentIdGet,
		},
		{
			"DeploymentPost",
			strings.ToUpper("Post"),
			"/v1/deployment",
			c.DeploymentPost,
		},
	}
}

// DeploymentDeploymentIdGet - Get the deployment with id deploymentId
func (c *DefaultApiController) DeploymentDeploymentIdGet(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	deploymentId := params["deploymentId"]
	result, err := c.service.DeploymentDeploymentIdGet(deploymentId)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// DeploymentPost - Create a new deployment
func (c *DefaultApiController) DeploymentPost(w http.ResponseWriter, r *http.Request) {
	err := r.ParseForm()
	if err != nil {
		w.WriteHeader(500)
		return
	}

	repository := r.FormValue("repository")
	email := r.FormValue("email")
	result, err := c.service.DeploymentPost(repository, email)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}
