/*
 * Parvaeres API
 *
 * Parvaeres magic deployment API
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	parvaeres "github.com/riccardomc/parvaeres/go"
)

func main() {
	log.Printf("Server started")

	DefaultApiService := parvaeres.NewDefaultApiService()
	DefaultApiController := parvaeres.NewDefaultApiController(DefaultApiService)

	router := parvaeres.NewRouter(DefaultApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
