/*
 * Parvaeres API
 *
 * Parvaeres magic deployment API
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package parvaeres

import (
	"encoding/json"
)

// DeploymentAcceptedResponse struct for DeploymentAcceptedResponse
type DeploymentAcceptedResponse struct {
	Repository *string `json:"repository,omitempty"`
	Email *string `json:"email,omitempty"`
	Message *string `json:"message,omitempty"`
	Result *string `json:"result,omitempty"`
}

// NewDeploymentAcceptedResponse instantiates a new DeploymentAcceptedResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentAcceptedResponse() *DeploymentAcceptedResponse {
	this := DeploymentAcceptedResponse{}
	return &this
}

// NewDeploymentAcceptedResponseWithDefaults instantiates a new DeploymentAcceptedResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentAcceptedResponseWithDefaults() *DeploymentAcceptedResponse {
	this := DeploymentAcceptedResponse{}
	return &this
}

// GetRepository returns the Repository field value if set, zero value otherwise.
func (o *DeploymentAcceptedResponse) GetRepository() string {
	if o == nil || o.Repository == nil {
		var ret string
		return ret
	}
	return *o.Repository
}

// GetRepositoryOk returns a tuple with the Repository field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentAcceptedResponse) GetRepositoryOk() (*string, bool) {
	if o == nil || o.Repository == nil {
		return nil, false
	}
	return o.Repository, true
}

// HasRepository returns a boolean if a field has been set.
func (o *DeploymentAcceptedResponse) HasRepository() bool {
	if o != nil && o.Repository != nil {
		return true
	}

	return false
}

// SetRepository gets a reference to the given string and assigns it to the Repository field.
func (o *DeploymentAcceptedResponse) SetRepository(v string) {
	o.Repository = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *DeploymentAcceptedResponse) GetEmail() string {
	if o == nil || o.Email == nil {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentAcceptedResponse) GetEmailOk() (*string, bool) {
	if o == nil || o.Email == nil {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *DeploymentAcceptedResponse) HasEmail() bool {
	if o != nil && o.Email != nil {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *DeploymentAcceptedResponse) SetEmail(v string) {
	o.Email = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *DeploymentAcceptedResponse) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentAcceptedResponse) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *DeploymentAcceptedResponse) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *DeploymentAcceptedResponse) SetMessage(v string) {
	o.Message = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *DeploymentAcceptedResponse) GetResult() string {
	if o == nil || o.Result == nil {
		var ret string
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentAcceptedResponse) GetResultOk() (*string, bool) {
	if o == nil || o.Result == nil {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *DeploymentAcceptedResponse) HasResult() bool {
	if o != nil && o.Result != nil {
		return true
	}

	return false
}

// SetResult gets a reference to the given string and assigns it to the Result field.
func (o *DeploymentAcceptedResponse) SetResult(v string) {
	o.Result = &v
}

func (o DeploymentAcceptedResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Repository != nil {
		toSerialize["repository"] = o.Repository
	}
	if o.Email != nil {
		toSerialize["email"] = o.Email
	}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	if o.Result != nil {
		toSerialize["result"] = o.Result
	}
	return json.Marshal(toSerialize)
}

type NullableDeploymentAcceptedResponse struct {
	value *DeploymentAcceptedResponse
	isSet bool
}

func (v NullableDeploymentAcceptedResponse) Get() *DeploymentAcceptedResponse {
	return v.value
}

func (v *NullableDeploymentAcceptedResponse) Set(val *DeploymentAcceptedResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentAcceptedResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentAcceptedResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentAcceptedResponse(val *DeploymentAcceptedResponse) *NullableDeploymentAcceptedResponse {
	return &NullableDeploymentAcceptedResponse{value: val, isSet: true}
}

func (v NullableDeploymentAcceptedResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentAcceptedResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


