---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: parvaeres-server
  name: parvaeres-server
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parvaeres-server
  template:
    metadata:
      labels:
        app: parvaeres-server
    spec:
      containers:
        - image: registry.localhost:5000/parvaeres:latest
          imagePullPolicy: Always
          name: parvaeres
          ports:
            - containerPort: 8080
      serviceAccount: parvaeres-server
      serviceAccountName: parvaeres-server
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: parvaeres-server
  name: parvaeres-server
  namespace: argocd
spec:
  ports:
    - name: api
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: parvaeres-server
  type: LoadBalancer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: parvaeres-server
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - create
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
      - namespaces
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - argoproj.io
    resources:
      - applications
      - appprojects
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - delete
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - list
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - services
    verbs:
      - get
      - list
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: parvaeres-server
  namespace: argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: parvaeres-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: parvaeres-server
subjects:
  - kind: ServiceAccount
    name: parvaeres-server
    namespace: argocd
