/*
 * Parvaeres API
 *
 * Parvaeres magic deployment API
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package parvaeres

type DeploymentAcceptedResponse struct {
	Repository string `json:"repository,omitempty"`

	Email string `json:"email,omitempty"`

	Message string `json:"message,omitempty"`

	Result string `json:"result,omitempty"`
}
