/*
 * Parvaeres API
 *
 * Parvaeres magic deployment API
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package parvaeres

type CreateDeploymentRequest struct {
	Email string `json:"Email,omitempty"`

	Repository string `json:"Repository,omitempty"`
}
