on: [push]
name: Run tests
jobs:
  tests:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: run Go tests
      uses: cedrickring/golang-action@1.5.2
